### ISSUE TITLE
AttributeError: 'MultiDiGraph' object has no attribute 'nodes_iter'

### ISSUE THREAD

**Issue by KSWilkinson** [iit-Demokritos/community-Tracking-GED#1]
Python script was initialized through the Windows command prompt (Windows 10).  Windows shell output is below.  Thank you

C:\Python27\Lib\site-packages\community-Tracking-GED-master>python Tracker.py community_edges.json
Initialize inclusions dict start...
Traceback (most recent call last):
  File "Tracker.py", line 101, in <module>
    tracker.compare_communities()
  File "Tracker.py", line 32, in compare_communities
    Dhypergraph = self.initialize_inclusions(index,Dhypergraph)
  File "Tracker.py", line 71, in initialize_inclusions
    inclusion, inversed = inclusions.compute_inclusion()
  File "C:\Python27\Lib\site-packages\community-Tracking-GED-master\inclusion.py", line 14, in compute_inclusion
    inclusion, inversed_inclusion = self.find_inclusions(self.g1, self.g2)
  File "C:\Python27\Lib\site-packages\community-Tracking-GED-master\inclusion.py", line 98, in find_inclusions
    self.find_group_quality(intersection, g1_with_degrees))
  File "C:\Python27\Lib\site-packages\community-Tracking-GED-master\inclusion.py", line 37, in find_group_quality
    g1_sum = sum([d['centrality'] for node,d in g1.nodes_iter(data=True)])
AttributeError: 'MultiDiGraph' object has no attribute 'nodes_iter'

**Comment by gilcu3** [comment]
should be fixed by [pull request](https://github.com/iit-Demokritos/community-Tracking-GED/pull/2)

**Comment by dimitrv** [comment]
Hi, 
Thanks for the feedback, i will fix it.
Are you using the networkx-2.0 library?
